using System;

public enum CellEnum
{
	EMPTY_CELL = 0,
	BALL_START_CELL = 1,
	BONUS_CELL = 2,
	GOAL_LEFT_CELL = 3,
	GOAL_RIGHT_CELL = 4,
	GOAL_TOP_CELL = 5,
	GOAL_BOTTOM_CELL = 6,
	ENEMY_DEFENDER_CELL = 10,
	ENEMY_GOALKEEPER_CELL = 11,
	ALLY_DEFENDER_CELL = 20,
	ALLY_MIDFIELD_CELL = 21,
	ALLY_ATTACKER_CELL = 22,
	ALLY_GOALKEEPER_CELL = 23
}


